# Generated by Django 6.0 on 2026-01-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dress",
            name="name",
            field=models.CharField(default="Dress", max_length=100),
        ),
    ]
