# Generated by Django 6.0 on 2026-01-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_dress_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="dress",
            name="sizes",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
