# Generated by Django 6.0 on 2026-01-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_dress_sizes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="dress",
            name="sizes",
        ),
        migrations.AddField(
            model_name="dress",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="dresses", to="core.size"
            ),
        ),
    ]
