# Generated by Django 6.0 on 2026-01-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_size_remove_dress_sizes_dress_sizes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dress",
            options={
                "verbose_name": "Women Dress",
                "verbose_name_plural": "Women Dresses",
            },
        ),
        migrations.AlterField(
            model_name="dress",
            name="name",
            field=models.CharField(default="Product", max_length=100),
        ),
        migrations.AlterField(
            model_name="dress",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, related_name="%(class)s_sizes", to="core.size"
            ),
        ),
        migrations.CreateModel(
            name="HandmadeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Product", max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of public image URLs (e.g. ['https://...','https://...'])",
                    ),
                ),
                (
                    "sizes",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)s_sizes", to="core.size"
                    ),
                ),
            ],
            options={
                "verbose_name": "Handmade Item",
                "verbose_name_plural": "Handmade Items",
            },
        ),
        migrations.CreateModel(
            name="MenProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Product", max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of public image URLs (e.g. ['https://...','https://...'])",
                    ),
                ),
                (
                    "sizes",
                    models.ManyToManyField(
                        blank=True, related_name="%(class)s_sizes", to="core.size"
                    ),
                ),
            ],
            options={
                "verbose_name": "Men Product",
                "verbose_name_plural": "Men Products",
            },
        ),
    ]
