# Generated by Django 6.0 on 2026-01-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_dress_options_alter_dress_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="handmadeitem",
            name="image_urls",
        ),
        migrations.RemoveField(
            model_name="menproduct",
            name="image_urls",
        ),
        migrations.AddField(
            model_name="handmadeitem",
            name="image_urls_text",
            field=models.TextField(blank=True, help_text="Paste URLs one per line"),
        ),
        migrations.AddField(
            model_name="menproduct",
            name="image_urls_text",
            field=models.TextField(blank=True, help_text="Paste URLs one per line"),
        ),
    ]
